### ISSUE TITLE
[NON-DOCKER] error Java Heap Space

### ISSUE THREAD

**Issue by JefPresotto** [Frooodle/Stirling-PDF#214]
Boa tarde,
Gostaria de informar um erro ao usar o card para UNIR VÁRIOS PDFS, pois ao adicionar varios arquivos, é apresentado erro de memoria Heap no Java. Segue alguns screenshots e o codigo de erro.

------------------IMAGENS-----------------------
![Screenshot_1](https://github.com/Frooodle/Stirling-PDF/assets/48888772/977e17f8-7688-4c96-8e8d-00e52138a737)
![Screenshot_2](https://github.com/Frooodle/Stirling-PDF/assets/48888772/ee7c74d8-6c6b-449d-b9bd-3ad04072668c)
![Screenshot_3](https://github.com/Frooodle/Stirling-PDF/assets/48888772/0b15ac6c-875e-4d6c-97ee-b153144f0cf3)
![Screenshot_4](https://github.com/Frooodle/Stirling-PDF/assets/48888772/5010262c-9bd0-4e50-b516-4f994279a437)
----------------------------------------------------------------------------------------------------------

-------CODIGO DO ERRO-----
java.lang.OutOfMemoryError: Java heap space

        at org.apache.pdfbox.io.ScratchFileBuffer.addPage(ScratchFileBuffer.java:126) ~[pdfbox-2.0.28.jar:2.0.28]

        at org.apache.pdfbox.io.ScratchFileBuffer.ensureAvailableBytesInPage(ScratchFileBuffer.java:178) ~[pdfbox-2.0.28.jar:2.0.28]

        at org.apache.pdfbox.io.ScratchFileBuffer.write(ScratchFileBuffer.java:230) ~[pdfbox-2.0.28.jar:2.0.28]

        at org.apache.pdfbox.io.ScratchFile.createBuffer(ScratchFile.java:462) ~[pdfbox-2.0.28.jar:2.0.28]

        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1231) ~[pdfbox-2.0.28.jar:2.0.28]

        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1133) ~[pdfbox-2.0.28.jar:2.0.28]

        at stirling.software.SPDF.controller.api.MergeController.mergePdfs(MergeController.java:61) ~[main/:na]

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.8.jar:6.0.8]

        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.8.jar:6.0]

        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.8.jar:6.0.8]

        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.8.jar:6.0]

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.8.jar:10.1.8]

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.8.jar:10.1.8]

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.8.jar:10.1.8]

        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.8.jar:6.0.8]

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.8.jar:6.0.8]

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.8.jar:10.1.8]
-----------------------------------------------------------------------------

Tentei resolver alterando o tamanho do heap no arquivo ~/gradlew, mas também não funcionou. Segue imagem.
![Screenshot_5](https://github.com/Frooodle/Stirling-PDF/assets/48888772/21b8e5d9-623e-4282-9b50-240cb74713f1)

Logo, também tentei utilizar os comandos abaixo no terminal:
sudo export _JAVA_OPTIONS="-Xmx2048m"
sudo export _JAVA_OPTIONS="-Xms2048m"

Não sei dizer se é necessario alguma alteração também do MaxPermSize, ou alguma alteração dentro do CATALINA do tomcat (conforme andei pesquisando na web), mas não sei se é verdade!

Novamente, obrigado pelo apoio!

**Comment by JefPresotto** [comment]
Mais uma pergunta,  há limitação da quantidade de arquivos para unir? ou o limite esta relacionado ao tamanho dos arquivos em mb?

**Comment by Frooodle** [comment]
How do you run the app? Are you using java -jar or something different like gradlew bootRun?

Also, there is no limit on merge, i just tested it with 85 5kb pdf files and it works fine so its 100% heap related.
Might be worth seeing how much stirling PDF uses to in memory to do these merges i dont know if it could use more than 2gb for 500mb of files due to how it has to store and load it all
maybe it needs 3gb haha
or the Xmx2048m isnt working

**Comment by JefPresotto** [comment]
Obrigado pela resposta, eu utilizo o gradlew bootRun para iniciar a aplicação. Vou tentar aumentar o tamanho do heap para 4gb.. estou testando a carga de arquivos em todos os cards para ver o limite maximo de cada um, tanto de memória, quanto de arquivos. Logo que testar vou colocar aqui no post o resultado do heap de 4gb.
