### ISSUE TITLE
OCR error

### ISSUE THREAD

**Issue by webysther** [Frooodle/Stirling-PDF#267]
I added some languages and with this configuration:

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/847f07f7-62cf-48d5-868c-cd315bfe8d6a)

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/4c73bb03-c16e-4c64-aa57-9e391847e3bd)

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/debabeb2-58fb-4f4e-8025-f8d33e12cc02)

```
app-pdf  | Running command: ocrmypdf --verbose 2 --output-type pdf --pdf-renderer hocr --skip-text --language eng+ita+por /tmp/input_15454039178197752710.pdf /tmp/output_9015542322091627730.pdfCommand error output:
app-pdf  |   DEBUG ocrmypdf - ocrmypdf 10.3.1+dfsg
app-pdf  |   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
app-pdf  |   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
app-pdf  |   DEBUG ocrmypdf.subprocess - Found tesseract 4.1.1
app-pdf  |   DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
app-pdf  |   DEBUG ocrmypdf.subprocess - Found gs 9.53.3
app-pdf  |   DEBUG ocrmypdf.helpers - pikepdf mmap enabled
app-pdf  |   DEBUG ocrmypdf.helpers - os.symlink(/tmp/input_15454039178197752710.pdf, /tmp/com.github.ocrmypdf.93dqwwrs/origin)
app-pdf  |   DEBUG ocrmypdf.helpers - os.symlink(/tmp/com.github.ocrmypdf.93dqwwrs/origin, /tmp/com.github.ocrmypdf.93dqwwrs/origin.pdf)
app-pdf  |   DEBUG ocrmypdf.helpers - pikepdf mmap enabled
app-pdf  |    INFO ocrmypdf.builtin_plugins.tesseract_ocr - Using Tesseract OpenMP thread limit 3
app-pdf  |   DEBUG ocrmypdf.helpers - pikepdf mmap enabled
app-pdf  |   DEBUG ocrmypdf._pipeline -    1  Rasterize with png16m
app-pdf  |   DEBUG ocrmypdf.subprocess -    1  Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r181.135352x181.135352', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/com.github.ocrmypdf.93dqwwrs/origin.pdf']
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2354
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'default_rgb.icc'
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  Compression method 0
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2407 9
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'tEXt' 2428 31
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2471 8192
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2350
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'ICC Profile'
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  Compression method 0
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2403 9
app-pdf  |   DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2424 65536
app-pdf  |   DEBUG ocrmypdf._pipeline -    1  resolution (181, 181)
app-pdf  |   DEBUG ocrmypdf.subprocess -    1  Running: ['tesseract', '-l', 'por+eng+ita', PosixPath('/tmp/com.github.ocrmypdf.93dqwwrs/000001_ocr.png'), PosixPath('/tmp/com.github.ocrmypdf.93dqwwrs/000001_ocr_hocr'), 'hocr', 'txt']
app-pdf  |   ERROR ocrmypdf._exec.tesseract -    1  [tesseract] read_params_file: Can't open hocr
app-pdf  |   ERROR ocrmypdf._exec.tesseract -    1  [tesseract] read_params_file: Can't open txt
app-pdf  |   ERROR ocrmypdf._exec.tesseract -    1  [tesseract] read_params_file: Can't open hocr
app-pdf  |   ERROR ocrmypdf._exec.tesseract -    1  [tesseract] read_params_file: Can't open txt
app-pdf  |   ERROR ocrmypdf._exec.tesseract -    1  [tesseract] read_params_file: Can't open hocr
app-pdf  |   ERROR ocrmypdf._exec.tesseract -    1  [tesseract] read_params_file: Can't open txt
app-pdf  | WARNING ocrmypdf._exec.tesseract -    1  [tesseract] lots of diacritics - possibly poor OCR
app-pdf  |   ERROR ocrmypdf._sync - An exception occurred while executing the pipeline
app-pdf  | multiprocessing.pool.RemoteTraceback: 
app-pdf  | """
app-pdf  | Traceback (most recent call last):
app-pdf  |   File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
app-pdf  |     result = (True, func(*args, **kwds))
app-pdf  |   File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 221, in exec_page_sync
app-pdf  |     ocr_out = render_hocr_page(hocr_out, page_context)
app-pdf  |   File "/usr/lib/python3/dist-packages/ocrmypdf/_pipeline.py", line 612, in render_hocr_page
app-pdf  |     hocrtransform = HocrTransform(hocr, dpi.x)  # square
app-pdf  |   File "/usr/lib/python3/dist-packages/ocrmypdf/hocrtransform.py", line 74, in __init__
app-pdf  |     self.hocr = ElementTree.parse(os.fspath(hocr_filename))
app-pdf  |   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
app-pdf  |     tree.parse(source, parser)
app-pdf  |   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
app-pdf  |     source = open(source, "rb")
app-pdf  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/com.github.ocrmypdf.93dqwwrs/000001_ocr_hocr.hocr'
app-pdf  | 2023-07-10T12:22:14.526Z ERROR 1 --- [io-8080-exec-23] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
app-pdf  | 
app-pdf  | 
app-pdf  | java.io.IOException: Command process failed with exit code 15. Error message:   DEBUG ocrmypdf - ocrmypdf 10.3.1+dfsg
app-pdf  |   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
app-pdf  |   DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
app-pdf  |   DEBUG ocrmypdf.subprocess - Found tesseract 4.1.1
app-pdf  |   DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
app-pdf  |   DEBUG ocrmypdf.subprocess - Found gs 9.53.3
app-pdf  | 2023-07-10T12:22:14.561Z ERROR 1 --- [io-8080-exec-23] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]
app-pdf  | 
app-pdf  | 
app-pdf  | org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
app-pdf  |      at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:305) ~[tomcat-embed-core-10.1.10.jar!/:na]
app-pdf  |      at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:267) ~[tomcat-embed-core-10.1.10.jar!/:na]
app-pdf  |      at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:120) ~[tomcat-embed-core-10.1.10.jar!/:na]
```

I miss something?

**Comment by webysther** [comment]
Found the problem: Ignore pages will fail if no text where found.

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/203b1c16-d821-491a-a963-46f5cc53b8d8)
