### ISSUE TITLE
config directory is created on startup (possible typo of 'configs')

### ISSUE THREAD

**Issue by gramakri** [Frooodle/Stirling-PDF#339]
In the Cloudron package, I see an exception on startup. Cloudron creates container as readonly, so it doesn't allow arbitrary file creation. The code is trying to create a `config` directory. My understanding is this has to be `configs`.

```
08:28:51 - java.nio.file.FileSystemException: /app/code/config: Read-only file system
08:28:51 - at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
08:28:51 - at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
08:28:51 - at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
08:28:51 - at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
08:28:51 - at java.base/java.nio.file.Files.createDirectory(Files.java:700)
08:28:51 - at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
08:28:51 - at java.base/java.nio.file.Files.createDirectories(Files.java:793)
08:28:51 - at stirling.software.SPDF.utils.GeneralUtils.createDir(GeneralUtils.java:145)
08:28:51 - at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:69)
08:28:51 - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:28:51 - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
08:28:51 - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:28:51 - at java.base/java.lang.reflect.Method.invoke(Method.java:568)
08:28:51 - at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
08:28:51 - at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
08:28:51 - at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
08:28:51 - at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

**Comment by gramakri** [comment]
The code is https://github.com/Frooodle/Stirling-PDF/blob/main/src/main/java/stirling/software/SPDF/SPdfApplication.java#L69 . I guess this should be `configs` ?

**Comment by Frooodle** [comment]
Correct I actually have this fixed in the next release I am working on

**Comment by Frooodle** [comment]
Appreciate you pointing it out 
Only noticed yesterday

**Comment by gramakri** [comment]
Ah ok :-) Guess we can close this one then.
