### ISSUE TITLE
Error after upgraded to latest version

### ISSUE THREAD

**Issue by ikerib** [Frooodle/Stirling-PDF#362]
I docker compose pull && composer compose run -d and I'm gettin this error now. It was working ok before:

```
docker-stirling-pdf-1  | Copying original files without overwriting existing files
docker-stirling-pdf-1  | Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
docker-stirling-pdf-1  | 
docker-stirling-pdf-1  |   .   ____          _            __ _ _
docker-stirling-pdf-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
docker-stirling-pdf-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
docker-stirling-pdf-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
docker-stirling-pdf-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
docker-stirling-pdf-1  |  =========|_|==============|___/=/_/_/_/
docker-stirling-pdf-1  |  :: Spring Boot ::                (v3.1.2)
docker-stirling-pdf-1  | 
docker-stirling-pdf-1  | 2023-09-14T15:28:45.448Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
docker-stirling-pdf-1  | 
docker-stirling-pdf-1  | java.lang.RuntimeException: Failed to initialize application configuration
docker-stirling-pdf-1  | 	at stirling.software.SPDF.config.ConfigInitializer.initialize(ConfigInitializer.java:27) ~[classes!/:0.14.0]
docker-stirling-pdf-1  | 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:607) ~[spring-boot-3.1.2.jar!/:3.1.2]
docker-stirling-pdf-1  | 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:387) ~[spring-boot-3.1.2.jar!/:3.1.2]
docker-stirling-pdf-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.2.jar!/:3.1.2]
docker-stirling-pdf-1  | 	at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:57) ~[classes!/:0.14.0]
docker-stirling-pdf-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
docker-stirling-pdf-1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:0.14.0]
docker-stirling-pdf-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[app.jar:0.14.0]
docker-stirling-pdf-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:0.14.0]
docker-stirling-pdf-1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[app.jar:0.14.0]
docker-stirling-pdf-1  | Caused by: java.nio.file.AccessDeniedException: configs/settings.yml
docker-stirling-pdf-1  | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/java.nio.file.Files.newOutputStream(Files.java:228) ~[na:na]
docker-stirling-pdf-1  | 	at java.base/java.nio.file.Files.write(Files.java:3581) ~[na:na]
docker-stirling-pdf-1  | 	at stirling.software.SPDF.config.ConfigInitializer.mergeYamlFiles(ConfigInitializer.java:99) ~[classes!/:0.14.0]
docker-stirling-pdf-1  | 	at stirling.software.SPDF.config.ConfigInitializer.ensureConfigExists(ConfigInitializer.java:55) ~[classes!/:0.14.0]
docker-stirling-pdf-1  | 	at stirling.software.SPDF.config.ConfigInitializer.initialize(ConfigInitializer.java:25) ~[classes!/:0.14.0]
docker-stirling-pdf-1  | 	... 12 common frames omitted
docker-stirling-pdf-1  | 
docker-stirling-pdf-1 exited with code 1
```

**Comment by LapinFou** [comment]
Same for me.
Docker is running on Synology NAS through Portainer.
FYI, I already switched to the new settings.yml config file.
Rolling back to version 13.1 worked until the version 14 is fixed. 😊

**Comment by Frooodle** [comment]
made a 0.14.1 should hopefully fix, let me know!

**Comment by ikerib** [comment]
it's working now! Thx!!
