### ISSUE TITLE
Container doesn't work when using "latest-lite" image

### ISSUE THREAD

**Issue by ShlomiD83** [Frooodle/Stirling-PDF#387]
Hi,
When using the "latest-lite" image the container doesn't work, but when using the "latest" or "latest-ultra-lite" it works fine.
here are the logs..

2023-09-28T18:51:32.394759710Z   .   ____          _            __ _ _
2023-09-28T18:51:32.394769861Z  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2023-09-28T18:51:32.394899113Z ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2023-09-28T18:51:32.394914289Z  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2023-09-28T18:51:32.394922776Z   '  |____| .__|_| |_|_| |_\__, | / / / /
2023-09-28T18:51:32.394931056Z  =========|_|==============|___/=/_/_/_/
2023-09-28T18:51:32.396378172Z  :: Spring Boot ::                (v3.1.2)
2023-09-28T18:51:32.396413689Z 
2023-09-28T18:51:32.827878434Z 2023-09-28T21:51:32.818+03:00 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2023-09-28T18:51:32.827920726Z 
2023-09-28T18:51:32.827932579Z java.lang.RuntimeException: Failed to initialize application configuration
2023-09-28T18:51:32.827941735Z 	at stirling.software.SPDF.config.ConfigInitializer.initialize(ConfigInitializer.java:29) ~[classes!/:0.14.3]
2023-09-28T18:51:32.827951096Z 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:607) ~[spring-boot-3.1.2.jar!/:3.1.2]
2023-09-28T18:51:32.827960251Z 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:387) ~[spring-boot-3.1.2.jar!/:3.1.2]
2023-09-28T18:51:32.827968717Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.2.jar!/:3.1.2]
2023-09-28T18:51:32.827977757Z 	at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:57) ~[classes!/:0.14.3]
2023-09-28T18:51:32.827986661Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-09-28T18:51:32.827995188Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2023-09-28T18:51:32.828003098Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2023-09-28T18:51:32.828010592Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2023-09-28T18:51:32.828017545Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:0.14.3]
2023-09-28T18:51:32.828024895Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[app.jar:0.14.3]
2023-09-28T18:51:32.828031877Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:0.14.3]
2023-09-28T18:51:32.828039154Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[app.jar:0.14.3]
2023-09-28T18:51:32.828068635Z Caused by: java.nio.file.AccessDeniedException: configs/settings.yml
2023-09-28T18:51:32.828077559Z 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
2023-09-28T18:51:32.828085241Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
2023-09-28T18:51:32.828092738Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
2023-09-28T18:51:32.828100268Z 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[na:na]
2023-09-28T18:51:32.828110453Z 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[na:na]
2023-09-28T18:51:32.828118041Z 	at java.base/java.nio.file.Files.newOutputStream(Files.java:228) ~[na:na]
2023-09-28T18:51:32.828125602Z 	at java.base/java.nio.file.Files.write(Files.java:3581) ~[na:na]
2023-09-28T18:51:32.828132788Z 	at stirling.software.SPDF.config.ConfigInitializer.mergeYamlFiles(ConfigInitializer.java:126) ~[classes!/:0.14.3]
2023-09-28T18:51:32.828140465Z 	at stirling.software.SPDF.config.ConfigInitializer.ensureConfigExists(ConfigInitializer.java:58) ~[classes!/:0.14.3]
2023-09-28T18:51:32.828147722Z 	at stirling.software.SPDF.config.ConfigInitializer.initialize(ConfigInitializer.java:27) ~[classes!/:0.14.3]
2023-09-28T18:51:32.828155287Z 	... 12 common frames omitted

Please assist..

**Comment by Frooodle** [comment]
fixed in 0.14.4
