### ISSUE TITLE
Remove Password doesn't work

### ISSUE THREAD

**Issue by AvMavs** [Frooodle/Stirling-PDF#51]
As the title says, Remove Password doesn't work. It just gives me a smaller file, albeit still being password-locked.

**Comment by aqnts** [comment]
Hello,

Here is an additional case of remove password is not working.
![decrypt_error](https://user-images.githubusercontent.com/71295212/219508195-4a165cf5-9ef4-491b-b53d-975224207ede.gif)

I used the pdf file encrypted by S-PDF, and tried to decrypt it using S-PDF, then it shows the error in attached gif image.

**Comment by Frooodle** [comment]
I'm away this weekend so will take a look first thing Monday 
Shouldn't be to hard to fix

As for that error, is there any logs on docker side you can share?

**Comment by aqnts** [comment]
Could you be more specific about logs on docker?
Do you mean by any error log created by web server within docker? If so, please let me know the location to look for them.

**Comment by AvMavs** [comment]
```02/17/2023 2:40:02 PM
org.apache.pdfbox.pdmodel.encryption.InvalidPasswordException: Cannot decrypt PDF, the password is incorrect
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdmodel.encryption.StandardSecurityHandler.prepareForDecryption(StandardSecurityHandler.java:284) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdfparser.COSParser.prepareDecryption(COSParser.java:2988) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdfparser.COSParser.retrieveTrailer(COSParser.java:285) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdfparser.PDFParser.initialParse(PDFParser.java:173) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:226) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1313) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1290) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1271) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1254) ~[pdfbox-2.0.27.jar!/:2.0.27]
02/17/2023 2:40:02 PM
	at stirling.software.SPDF.controller.security.PasswordController.compressPDF(PasswordController.java:60) ~[classes!/:na]
02/17/2023 2:40:02 PM
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
02/17/2023 2:40:02 PM
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
02/17/2023 2:40:02 PM
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
02/17/2023 2:40:02 PM
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
02/17/2023 2:40:02 PM
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.4.jar!/:6.0.4]
02/17/2023 2:40:02 PM
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.4.jar!/:6.0.4]
02/17/2023 2:40:02 PM
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
02/17/2023 2:40:02 PM
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
02/17/2023 2:40:02 PM
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
02/17/2023 2:40:02 PM
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.4.jar!/:6.0.4]```
	
I am sure that the password is correct because I've used it across various applications to open the same PDF.

**Comment by Frooodle** [comment]
Fixed for next update

**Comment by AvMavs** [comment]
Thank you!
