### ISSUE TITLE
problem while using the PDF to Image conversion function. 

### ISSUE THREAD

**Issue by ly40** [Frooodle/Stirling-PDF#540]
I encountered a problem while using the PDF to image conversion function.

How should I fix it?

`08:50:44.023 [http-nio-8080-exec-10] INFO  s.software.SPDF.utils.PdfUtils - Images successfully written to byte array as a zip
08:50:44.119 [http-nio-8080-exec-10] WARN  o.a.coyote.http11.Http11Processor - The HTTP response header [Content-Disposition] with value [attachment; filename=???_convertedToImages.zip] has been removed from the response because it is invalid
java.lang.IllegalArgumentException: The Unicode character [?] at code point [32,599] cannot be encoded as it is outside the permitted range of 0 to 255
        at org.apache.tomcat.util.buf.MessageBytes.toBytesSimple(MessageBytes.java:286)
        at org.apache.tomcat.util.buf.MessageBytes.toBytes(MessageBytes.java:259)
        at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:389)
        at org.apache.coyote.http11.Http11OutputBuffer.sendHeader(Http11OutputBuffer.java:368)
        at org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1051)
        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:376)
        at org.apache.coyote.Response.action(Response.java:208)
        at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:187)
        at org.apache.coyote.Response.doWrite(Response.java:613)
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:334)
        at org.apache.catalina.connector.OutputBuffer.appendByteArray(OutputBuffer.java:750)
        at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:677)
        at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:382)
        at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:360)
        at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:97)
        at java.base/java.io.ByteArrayInputStream.transferTo(ByteArrayInputStream.java:208)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:149)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:138)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:46)
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:225)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:300)
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:245)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:43)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:738)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by nawramm** [comment]
>  ... has been removed from the response because it is invalid java.lang.IllegalArgumentException: The Unicode character [?] at code point [32,599] cannot be encoded as it is outside the permitted range of 0 to 255

Looks like it errors because the filename has a non-ACSII character.

Try renaming the file as a workaround for now.

**Comment by ly40** [comment]
> > ... has been removed from the response because it is invalid java.lang.IllegalArgumentException: The Unicode character [?] at code point [32,599] cannot be encoded as it is outside the permitted range of 0 to 255
> 
> Looks like it errors because the filename has a non-ACSII character.
> 
> Try renaming the file as a workaround for now.

That's true, I have already solved this problem.

But I encountered another problem:
When the PDF file I upload is relatively large, such as when it is larger than 10MB, an error message will appear.
Java. lang.OutOfMemoryError: Java heap space

I have been unable to solve this problem.


`stirling-pdf  | 12:32:23.848 [http-nio-8080-exec-26] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.OutOfMemoryError: Java heap space] with root cause
stirling-pdf  | java.lang.OutOfMemoryError: Java heap space
stirling-pdf  |         at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
stirling-pdf  |         at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
stirling-pdf  |         at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
stirling-pdf  |         at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261)
stirling-pdf  |         at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
stirling-pdf  |         at java.base/java.util.zip.ZipOutputStream.write(ZipOutputStream.java:347)
stirling-pdf  |         at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
stirling-pdf  |         at stirling.software.SPDF.utils.PdfUtils.convertFromPdf(PdfUtils.java:237)
stirling-pdf  |         at stirling.software.SPDF.controller.api.converters.ConvertImgPDFController.convertToImage(ConvertImgPDFController.java:55)
stirling-pdf  |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
stirling-pdf  |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
stirling-pdf  |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
stirling-pdf  |         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
stirling-pdf  |         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
stirling-pdf  |         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
stirling-pdf  |         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
stirling-pdf  |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
stirling-pdf  |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
stirling-pdf  |         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
stirling-pdf  |         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
stirling-pdf  |         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
stirling-pdf  |         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
stirling-pdf  |         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
stirling-pdf  |         at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
stirling-pdf  |         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
stirling-pdf  |         at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
stirling-pdf  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
stirling-pdf  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf  |         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
stirling-pdf  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
stirling-pdf  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
stirling-pdf  |         at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:43)`

**Comment by Frooodle** [comment]
This means the server has ran out of memory

Can you monitor your ram during operation and see if it spikes to max?

**Comment by ly40** [comment]
> This means the server has ran out of memory
> 
> Can you monitor your ram during operation and see if it spikes to max?

I have no problem converting small files.

But when the file is relatively large, there will be a memory overflow.

I use Docker for deployment, and the machine has 24GB of memory. Every time there is a memory overflow error, the memory I monitor through Docker Stats does not exceed 6GB. I don't know how to set it up?

**Comment by Frooodle** [comment]
Are you using docker compose? What's your compose script like?  And have you done anything custom

**Comment by eXqusic92** [comment]
I have same issue with Java heap space while converting pdf to image (PDFs size approx. 10mb). My docker compose script looks like this
```
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - /mnt/sda1/s-pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - /home/exqusic/.config/stirling-pdf/configs:/configs
#      - /location/of/customFiles:/customFiles/
#      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
```
Also I have tried adding `mem_limit: 4g`, but this didn't help me. I have 4 Gb of RAM, and while converting RAM usage don't go higher than 1.5gb

**Comment by Frooodle** [comment]
let me investigate this now to see JVM sizing on docker

**Comment by Frooodle** [comment]
Can you please try run this command on the docker container and post back here

java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+PrintGCDetails -version

**Comment by Frooodle** [comment]
I believe the java env is running max 1/4 of the total memory available, ill see if i can add a flag to override this in the future

**Comment by eXqusic92** [comment]
`[0.001s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.
-XX:ConcGCThreads=1 -XX:G1ConcRefinementThreads=4 -XX:GCDrainStackTargetSize=64 -XX:InitialHeapSize=64322048 -XX:MarkStackSize=4194304 -XX:MaxHeapSize=1029152768 -XX:MinHeapSize=6815736 -XX:+PrintCommandLineFlags -XX:+PrintGCDetails -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC 
[0.007s][info   ][gc] Using G1
[0.009s][info   ][gc,init] Version: 17.0.9+9-Ubuntu-122.04 (release)
[0.009s][info   ][gc,init] CPUs: 4 total, 4 available
[0.009s][info   ][gc,init] Memory: 3925M
[0.009s][info   ][gc,init] Large Page Support: Disabled
[0.009s][info   ][gc,init] NUMA Support: Disabled
[0.009s][info   ][gc,init] Compressed Oops: Enabled (32-bit)
[0.009s][info   ][gc,init] Heap Region Size: 1M
[0.009s][info   ][gc,init] Heap Min Capacity: 8M
[0.009s][info   ][gc,init] Heap Initial Capacity: 62M
[0.009s][info   ][gc,init] Heap Max Capacity: 982M
[0.010s][info   ][gc,init] Pre-touch: Disabled
[0.010s][info   ][gc,init] Parallel Workers: 4
[0.010s][info   ][gc,init] Concurrent Workers: 1
[0.010s][info   ][gc,init] Concurrent Refinement Workers: 4
[0.010s][info   ][gc,init] Periodic GC: Disabled
[0.025s][info   ][gc,metaspace] CDS archive(s) mapped at: [0x0000004000000000-0x0000004000bc6000-0x0000004000bc6000), size 12345344, SharedBaseAddress: 0x0000004000000000, ArchiveRelocationMode: 1.
[0.025s][info   ][gc,metaspace] Compressed class space mapped at: 0x0000004001000000-0x0000004041000000, reserved size: 1073741824
[0.025s][info   ][gc,metaspace] Narrow klass base: 0x0000004000000000, Narrow klass shift: 0, Narrow klass range: 0x100000000
VM settings:
    Max. Heap Size (Estimated): 982.00M
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)
[0.045s][info   ][gc,heap,exit] Heap
[0.045s][info   ][gc,heap,exit]  garbage-first heap   total 65536K, used 1743K [0x00000000c2a00000, 0x0000000100000000)
[0.045s][info   ][gc,heap,exit]   region size 1024K, 1 young (1024K), 0 survivors (0K)
[0.045s][info   ][gc,heap,exit]  Metaspace       used 60K, committed 128K, reserved 1114112K
[0.045s][info   ][gc,heap,exit]   class space    used 5K, committed 64K, reserved 1048576K`

**Comment by Frooodle** [comment]
Memory: 3925M
Max. Heap Size (Estimated): 982.00M
Yeah seems its set to use 1/4
Will try address this to let it use 3/4 of it

**Comment by nawramm** [comment]
try setting `JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage={percentage here}` as an environment variable e.g.:
```
docker run -d \
  -p 8080:8080 \
  -e JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75 \
  frooodle/s-pdf:latest
```
or
```

**Comment by Frooodle** [comment]
Going to be hardcoding this to 75% for docker images

**Comment by sbplat** [comment]
Fixed in the latest release.
